name: Build
on:
  push:
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Configure and Build Project
        run: |
          cd formatter_lib
          cmake -B build
          cmake --build build
