name: cmake build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Configure Project
        uses: threeal/cmake-action@main
        
      - name: Build Project
        run: cmake --build build

